import { LucideIcon, FileImage, FileText, FileType, Image, Type, Layers, FileOutput, ScanText } from "lucide-react";

export interface Tool {
  id: string;
  name: string;
  slug: string;
  description: string;
  longDescription: string;
  icon: string;
  color: string;
  bgGradient: string;
  inputFormats: string[];
  outputFormat: string;
  category: "image" | "pdf" | "text" | "utility";
  featured: boolean;
  howTo: string[];
  features: string[];
  faqs: { q: string; a: string }[];
}

export const tools: Tool[] = [
  {
    id: "jpg-to-word",
    name: "JPG to Word",
    slug: "jpg-to-word",
    description: "Convert image text into an editable Word document using OCR technology",
    longDescription: "Extract text from JPG, JPEG, or PNG images and convert it into a fully editable Microsoft Word DOCX file. Our browser-based OCR engine processes your image locally — your file never leaves your device.",
    icon: "FileImage",
    color: "violet",
    bgGradient: "from-violet-500 to-purple-600",
    inputFormats: ["JPG", "JPEG", "PNG"],
    outputFormat: "DOCX",
    category: "image",
    featured: true,
    howTo: [
      "Upload your JPG, JPEG, or PNG image using the upload area",
      "Our OCR engine extracts text from the image automatically",
      "Preview the extracted text before downloading",
      "Download your fully editable Word DOCX file",
    ],
    features: [
      "Browser-based OCR — no server uploads needed",
      "Supports JPG, JPEG, and PNG formats",
      "Extracts printed text with high accuracy",
      "Download as standard .docx format",
      "Completely free with no registration",
      "Files never leave your device",
    ],
    faqs: [
      { q: "What image formats are supported?", a: "We support JPG, JPEG, and PNG image formats." },
      { q: "How accurate is the text extraction?", a: "Accuracy depends on image quality. Clear, high-contrast printed text typically achieves 90%+ accuracy. Handwritten text or low-quality images may have lower accuracy." },
      { q: "Is my image uploaded to a server?", a: "No. All processing happens in your browser using WebAssembly technology. Your image never leaves your device." },
      { q: "What is OCR?", a: "OCR (Optical Character Recognition) is technology that recognizes and extracts text from images." },
    ],
  },
  {
    id: "pdf-to-text",
    name: "PDF to Text",
    slug: "pdf-to-text",
    description: "Extract text from any PDF file quickly and accurately",
    longDescription: "Upload any PDF and instantly extract all readable text. Our tool first reads the PDF text layer directly (for digital PDFs), then uses OCR as a fallback for scanned documents. All processing is done in your browser.",
    icon: "FileText",
    color: "blue",
    bgGradient: "from-blue-500 to-cyan-600",
    inputFormats: ["PDF"],
    outputFormat: "TXT",
    category: "pdf",
    featured: true,
    howTo: [
      "Upload your PDF file by dragging or clicking the upload area",
      "The tool extracts text from all pages automatically",
      "Review the extracted text in the preview panel",
      "Download the result as a clean .txt file",
    ],
    features: [
      "Extracts text from native and scanned PDFs",
      "OCR fallback for image-based PDFs",
      "Multi-page support",
      "Download as .txt file",
      "Free and private — stays in your browser",
    ],
    faqs: [
      { q: "Will it work on scanned PDFs?", a: "Yes. For scanned PDFs without a text layer, OCR is applied automatically." },
      { q: "Is there a page limit?", a: "There is no hard page limit, though very large PDFs may take longer to process depending on your device." },
      { q: "What if the text looks wrong?", a: "Text formatting may not be fully preserved. For the most accurate results, use a native (non-scanned) PDF." },
    ],
  },
  {
    id: "pdf-to-word",
    name: "PDF to Word",
    slug: "pdf-to-word",
    description: "Convert your PDF into an editable Word document",
    longDescription: "Transform your PDF files into editable Microsoft Word DOCX documents. Text, paragraphs, and basic structure are preserved as much as possible during conversion, all processed locally in your browser.",
    icon: "FileType",
    color: "indigo",
    bgGradient: "from-indigo-500 to-blue-600",
    inputFormats: ["PDF"],
    outputFormat: "DOCX",
    category: "pdf",
    featured: true,
    howTo: [
      "Upload your PDF file",
      "Wait for the text extraction and conversion to complete",
      "Preview the extracted content",
      "Download your Word DOCX file",
    ],
    features: [
      "Converts native and scanned PDFs",
      "Preserves paragraph structure",
      "OCR for image-based PDFs",
      "Standard DOCX output compatible with Word",
      "Browser-based — your file stays private",
    ],
    faqs: [
      { q: "Will the formatting be exactly the same?", a: "Basic paragraph and text structure is preserved. Complex layouts like tables and multi-column formats may not transfer perfectly due to the nature of client-side conversion." },
      { q: "Can I edit the DOCX file in Google Docs?", a: "Yes, the .docx format is compatible with Microsoft Word, Google Docs, LibreOffice, and other word processors." },
    ],
  },
  {
    id: "text-to-pdf",
    name: "Text to PDF",
    slug: "text-to-pdf",
    description: "Convert plain text into a beautifully formatted PDF",
    longDescription: "Paste text or upload a .txt file and convert it to a professional PDF. Customize page size, margins, font size, and line spacing to get the exact output you need.",
    icon: "FileOutput",
    color: "emerald",
    bgGradient: "from-emerald-500 to-teal-600",
    inputFormats: ["TXT", "Plain Text"],
    outputFormat: "PDF",
    category: "text",
    featured: false,
    howTo: [
      "Paste your text or upload a .txt file",
      "Choose page size, font, margins, and spacing",
      "Preview your PDF layout",
      "Download your formatted PDF",
    ],
    features: [
      "Customizable page size (A4, Letter, etc.)",
      "Adjustable margins and line spacing",
      "Font size control",
      "Multiple font options",
      "Instant browser-based conversion",
    ],
    faqs: [
      { q: "What page sizes are supported?", a: "A4, US Letter, A3, and Legal page sizes are supported." },
      { q: "Can I upload a .txt file?", a: "Yes, you can either paste text directly or upload a .txt file." },
    ],
  },
  {
    id: "text-to-word",
    name: "Text to Word",
    slug: "text-to-word",
    description: "Convert plain text into a formatted Word DOCX file",
    longDescription: "Paste your text or upload a .txt file and get a formatted Microsoft Word DOCX document. Add a title, choose your font, line spacing, and margins before downloading.",
    icon: "Type",
    color: "orange",
    bgGradient: "from-orange-500 to-amber-600",
    inputFormats: ["TXT", "Plain Text"],
    outputFormat: "DOCX",
    category: "text",
    featured: false,
    howTo: [
      "Paste your text or upload a .txt file",
      "Optionally add a title and choose formatting options",
      "Click Convert to generate your DOCX",
      "Download your Word document",
    ],
    features: [
      "Custom document title",
      "Font and size selection",
      "Margin and spacing control",
      "Standard .docx format output",
      "No registration needed",
    ],
    faqs: [
      { q: "Can I add a title to the document?", a: "Yes, you can add a title that will appear as a heading in the document." },
      { q: "What fonts are available?", a: "We support common document fonts including Arial, Times New Roman, and Calibri." },
    ],
  },
  {
    id: "text-to-image",
    name: "Text to Image",
    slug: "text-to-image",
    description: "Convert text into a downloadable PNG or JPG image",
    longDescription: "Type or paste any text and turn it into a custom image. Choose font, size, color, background, alignment, and canvas size. Export as PNG or JPG with a live real-time preview.",
    icon: "Image",
    color: "pink",
    bgGradient: "from-pink-500 to-rose-600",
    inputFormats: ["Plain Text"],
    outputFormat: "PNG / JPG",
    category: "text",
    featured: false,
    howTo: [
      "Type or paste your text into the editor",
      "Customize font, size, colors, alignment, and background",
      "See a live preview of your image",
      "Download as PNG or JPG",
    ],
    features: [
      "Live real-time preview",
      "Custom font, size, and color",
      "Background color and padding control",
      "Alignment options (left, center, right)",
      "Export as PNG or JPG",
      "Custom image dimensions",
    ],
    faqs: [
      { q: "What is the maximum image size?", a: "You can set custom image dimensions up to 4000x4000 pixels." },
      { q: "Can I make a transparent background?", a: "PNG export supports transparent backgrounds when you choose transparent as the background option." },
    ],
  },
  {
    id: "image-to-pdf",
    name: "Image to PDF",
    slug: "image-to-pdf",
    description: "Merge one or multiple images into a single PDF file",
    longDescription: "Upload one or more images and combine them into a single PDF. Drag and drop to reorder pages, choose page size, and download your finished PDF instantly. All processing stays in your browser.",
    icon: "Layers",
    color: "teal",
    bgGradient: "from-teal-500 to-green-600",
    inputFormats: ["JPG", "JPEG", "PNG", "WebP"],
    outputFormat: "PDF",
    category: "image",
    featured: true,
    howTo: [
      "Upload one or multiple images",
      "Drag and drop to reorder pages",
      "Choose page size and orientation",
      "Download your merged PDF",
    ],
    features: [
      "Multi-image support",
      "Drag-and-drop page reordering",
      "Page size options (A4, Letter)",
      "Maintains image quality",
      "All done in your browser — private",
    ],
    faqs: [
      { q: "How many images can I add?", a: "You can add as many images as your device memory allows. There is no hard limit." },
      { q: "Can I reorder the pages?", a: "Yes. After uploading, you can drag and drop images to set the order they appear in the PDF." },
    ],
  },
  {
    id: "image-to-text",
    name: "Image to Text (OCR)",
    slug: "image-to-text",
    description: "Extract text from any image using OCR technology",
    longDescription: "Upload any image containing text — photos, screenshots, scanned documents — and instantly extract all readable text using optical character recognition. The text can then be copied or downloaded as a .txt file.",
    icon: "ScanText",
    color: "cyan",
    bgGradient: "from-cyan-500 to-blue-600",
    inputFormats: ["JPG", "JPEG", "PNG", "WebP", "BMP"],
    outputFormat: "TXT",
    category: "image",
    featured: false,
    howTo: [
      "Upload your image (photo, screenshot, or scan)",
      "Wait for the OCR engine to process the image",
      "Review the extracted text in the preview",
      "Copy to clipboard or download as .txt",
    ],
    features: [
      "Supports 100+ languages",
      "Works with photos, screenshots, scans",
      "Copy text to clipboard",
      "Download as .txt file",
      "100% browser-based — private and secure",
    ],
    faqs: [
      { q: "Does it work with handwriting?", a: "Tesseract OCR has limited handwriting recognition. Clear, printed text gives the best results." },
      { q: "What languages does it support?", a: "The OCR engine supports over 100 languages including English, Spanish, French, German, Chinese, Arabic, and more." },
      { q: "Is it free?", a: "Yes, completely free with no registration or account required." },
    ],
  },
  {
    id: "pdf-to-images",
    name: "PDF to Images",
    slug: "pdf-to-images",
    description: "Convert every PDF page into a JPG or PNG image",
    longDescription: "Upload a PDF and convert each page into a high-quality JPG or PNG image. Download all pages as a ZIP archive or save individual pages one by one. All conversion happens in your browser.",
    icon: "FileImage",
    color: "purple",
    bgGradient: "from-purple-500 to-violet-600",
    inputFormats: ["PDF"],
    outputFormat: "JPG / PNG",
    category: "pdf",
    featured: false,
    howTo: [
      "Upload your PDF file",
      "Choose output format: JPG or PNG",
      "Preview each converted page",
      "Download all pages as a ZIP or save individually",
    ],
    features: [
      "Converts every page to an image",
      "Choose JPG or PNG output",
      "Adjustable image resolution (DPI)",
      "Download all as ZIP or individual pages",
      "Browser-based — your PDF never leaves your device",
    ],
    faqs: [
      { q: "What resolution are the output images?", a: "Default output is at 150 DPI, which is suitable for screen use. For print-quality output, use a high-resolution PDF." },
      { q: "Can I download only specific pages?", a: "Yes. After conversion, you can download all pages as a ZIP or click to download individual pages." },
    ],
  },
  // ─── IMAGE TOOLS ──────────────────────────────────────────────────────────
  {
    id: "image-resizer",
    name: "Image Resizer",
    slug: "image-resizer",
    description: "Resize images to any dimension without losing quality",
    longDescription: "Upload any image and resize it to exact pixel dimensions or by percentage. Preserve aspect ratio or set custom width and height. Download the resized image as PNG or JPG instantly, all in your browser.",
    icon: "Image",
    color: "violet",
    bgGradient: "from-violet-500 to-purple-600",
    inputFormats: ["JPG", "PNG", "WebP", "BMP"],
    outputFormat: "PNG / JPG",
    category: "image",
    featured: false,
    howTo: [
      "Upload your image file",
      "Enter the desired width and height in pixels, or set a percentage",
      "Choose whether to lock the aspect ratio",
      "Download your resized image",
    ],
    features: [
      "Resize by exact pixels or percentage",
      "Aspect ratio lock option",
      "Supports JPG, PNG, WebP, and BMP input",
      "Instant browser-based processing",
      "No upload to any server",
    ],
    faqs: [
      { q: "Will the image lose quality when resized?", a: "Enlarging images beyond their original size will reduce sharpness. Reducing size generally maintains good quality." },
      { q: "Can I resize to any dimension?", a: "Yes, you can set any custom pixel dimensions." },
    ],
  },
  {
    id: "image-compressor",
    name: "Image Compressor",
    slug: "image-compressor",
    description: "Compress images to reduce file size while preserving quality",
    longDescription: "Reduce the file size of your images without visible quality loss. Adjust the compression level and download the optimized image. Perfect for web use, email attachments, and storage savings. All in-browser, no uploads.",
    icon: "FileImage",
    color: "emerald",
    bgGradient: "from-emerald-500 to-teal-600",
    inputFormats: ["JPG", "PNG", "WebP"],
    outputFormat: "JPG / PNG",
    category: "image",
    featured: false,
    howTo: [
      "Upload your image",
      "Adjust the compression quality slider",
      "See the before and after file size comparison",
      "Download your compressed image",
    ],
    features: [
      "Adjustable compression quality slider",
      "Before/after size comparison",
      "Supports JPG, PNG, and WebP",
      "No quality compromise for moderate compression",
      "100% browser-based — private",
    ],
    faqs: [
      { q: "How much can I compress an image?", a: "Depending on the original, you can typically reduce file size by 50-80% with minimal visible quality loss." },
      { q: "What formats can I compress?", a: "We support JPG, PNG, and WebP formats." },
    ],
  },
  {
    id: "image-converter",
    name: "Image Converter",
    slug: "image-converter",
    description: "Convert images between JPG, PNG, WebP, and BMP formats",
    longDescription: "Easily convert images from one format to another. Transform JPG to PNG, PNG to WebP, WebP to JPG, and more. All conversions happen instantly in your browser with no server uploads required.",
    icon: "Image",
    color: "blue",
    bgGradient: "from-blue-500 to-cyan-600",
    inputFormats: ["JPG", "PNG", "WebP", "BMP"],
    outputFormat: "JPG / PNG / WebP",
    category: "image",
    featured: false,
    howTo: [
      "Upload your image file",
      "Select the target output format",
      "Click Convert",
      "Download your converted image",
    ],
    features: [
      "Convert between JPG, PNG, WebP, and BMP",
      "Maintains image quality during conversion",
      "Instant in-browser conversion",
      "No file size limits",
      "Private — no server uploads",
    ],
    faqs: [
      { q: "Can I convert PNG with transparency to JPG?", a: "Yes, though JPG does not support transparency, so transparent areas will be filled with a white background." },
      { q: "Will the image quality change?", a: "For lossless formats like PNG, quality is fully preserved. For JPG, a high-quality setting is used by default." },
    ],
  },
  {
    id: "image-watermark",
    name: "Image Watermark",
    slug: "image-watermark",
    description: "Add a custom text or image watermark to your photos",
    longDescription: "Protect your images by adding a custom text watermark. Choose position, opacity, font size, and color. Your images are processed entirely in the browser so they never leave your device.",
    icon: "Layers",
    color: "pink",
    bgGradient: "from-pink-500 to-rose-600",
    inputFormats: ["JPG", "PNG", "WebP"],
    outputFormat: "PNG / JPG",
    category: "image",
    featured: false,
    howTo: [
      "Upload the image you want to watermark",
      "Type your watermark text and customize its style",
      "Choose position, opacity, and font size",
      "Download the watermarked image",
    ],
    features: [
      "Custom text watermark",
      "Control position, opacity, and size",
      "Font color and style options",
      "Works with JPG, PNG, and WebP",
      "100% private — processed in browser",
    ],
    faqs: [
      { q: "Can I add an image watermark instead of text?", a: "Currently, text watermarks are supported. Image watermarking is planned for a future update." },
      { q: "Will the watermark be permanent?", a: "Yes, once downloaded, the watermark is embedded into the image." },
    ],
  },
  // ─── PDF TOOLS ────────────────────────────────────────────────────────────
  {
    id: "pdf-merge",
    name: "PDF Merger",
    slug: "pdf-merge",
    description: "Combine multiple PDF files into one single document",
    longDescription: "Upload two or more PDF files and merge them into a single PDF. Drag to reorder files before merging. Perfect for combining contracts, reports, or any multi-part documents. All done in your browser.",
    icon: "FileText",
    color: "blue",
    bgGradient: "from-blue-500 to-indigo-600",
    inputFormats: ["PDF"],
    outputFormat: "PDF",
    category: "pdf",
    featured: false,
    howTo: [
      "Upload two or more PDF files",
      "Drag to reorder them as needed",
      "Click Merge PDFs",
      "Download your combined PDF",
    ],
    features: [
      "Merge unlimited PDF files",
      "Drag-and-drop reordering",
      "Preserves original formatting",
      "Fast in-browser merging",
      "No file upload to servers",
    ],
    faqs: [
      { q: "How many PDFs can I merge at once?", a: "You can merge as many PDFs as your device memory allows. There is no hard limit." },
      { q: "Will the order of pages be preserved?", a: "Yes. The pages will appear in the order you arrange the files." },
    ],
  },
  {
    id: "pdf-split",
    name: "PDF Splitter",
    slug: "pdf-split",
    description: "Split a PDF into individual pages or custom page ranges",
    longDescription: "Upload a PDF and extract individual pages or split it into custom ranges. Download each part as a separate PDF file. All processing is done in your browser — no uploads required.",
    icon: "FileOutput",
    color: "orange",
    bgGradient: "from-orange-500 to-amber-600",
    inputFormats: ["PDF"],
    outputFormat: "PDF",
    category: "pdf",
    featured: false,
    howTo: [
      "Upload your PDF file",
      "Choose to split by page range or extract all pages",
      "Preview the split result",
      "Download the individual PDF parts",
    ],
    features: [
      "Split by custom page ranges",
      "Extract individual pages",
      "Download split parts as separate PDFs",
      "Browser-based — fully private",
      "No page limit",
    ],
    faqs: [
      { q: "Can I split a PDF into every single page?", a: "Yes. You can extract each page as its own separate PDF file." },
      { q: "What is the maximum file size?", a: "There is no enforced limit, though very large PDFs may be slower to process depending on your device." },
    ],
  },
  // ─── UTILITY TOOLS ────────────────────────────────────────────────────────
  {
    id: "word-counter",
    name: "Word Counter",
    slug: "word-counter",
    description: "Count words, characters, sentences, and reading time instantly",
    longDescription: "Paste or type any text and instantly get word count, character count, sentence count, paragraph count, and estimated reading time. Useful for essays, articles, social media posts, and more.",
    icon: "Type",
    color: "teal",
    bgGradient: "from-teal-500 to-cyan-600",
    inputFormats: ["Plain Text"],
    outputFormat: "Stats",
    category: "utility",
    featured: false,
    howTo: [
      "Paste or type your text into the editor",
      "Instantly see word count, character count, and more",
      "Check reading time estimates",
      "Copy or clear the text as needed",
    ],
    features: [
      "Real-time word and character count",
      "Sentence and paragraph count",
      "Estimated reading time",
      "No registration required",
      "100% private — stays in browser",
    ],
    faqs: [
      { q: "Does it count spaces in characters?", a: "Both counts are shown: characters with spaces and characters without spaces." },
      { q: "How is reading time estimated?", a: "Reading time is calculated at an average speed of 200 words per minute." },
    ],
  },
  {
    id: "case-converter",
    name: "Case Converter",
    slug: "case-converter",
    description: "Convert text between UPPERCASE, lowercase, Title Case, and more",
    longDescription: "Transform any text between multiple case formats: UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case. Instant in-browser conversion with a single click.",
    icon: "Type",
    color: "indigo",
    bgGradient: "from-indigo-500 to-purple-600",
    inputFormats: ["Plain Text"],
    outputFormat: "Text",
    category: "utility",
    featured: false,
    howTo: [
      "Paste or type your text",
      "Click the case format you want",
      "The converted text appears instantly",
      "Copy the result with one click",
    ],
    features: [
      "UPPERCASE, lowercase, Title Case, Sentence case",
      "camelCase, PascalCase, snake_case, kebab-case",
      "One-click copy to clipboard",
      "No character limit",
      "Instant conversion",
    ],
    faqs: [
      { q: "What case formats are supported?", a: "We support UPPERCASE, lowercase, Title Case, Sentence case, camelCase, PascalCase, snake_case, and kebab-case." },
      { q: "Is there a text length limit?", a: "No, you can convert text of any length." },
    ],
  },
  {
    id: "base64",
    name: "Base64 Encoder / Decoder",
    slug: "base64",
    description: "Encode or decode text and files using Base64 encoding",
    longDescription: "Encode any text string to Base64 or decode a Base64 string back to plain text. Also supports encoding image files to a Base64 data URI. Useful for developers embedding data in HTML, CSS, or APIs.",
    icon: "FileType",
    color: "purple",
    bgGradient: "from-purple-500 to-violet-600",
    inputFormats: ["Plain Text", "File"],
    outputFormat: "Base64 / Text",
    category: "utility",
    featured: false,
    howTo: [
      "Choose to encode or decode",
      "Paste your text or upload a file",
      "Click Encode or Decode",
      "Copy the result to your clipboard",
    ],
    features: [
      "Text to Base64 encoding",
      "Base64 to text decoding",
      "File to Base64 data URI encoding",
      "One-click copy to clipboard",
      "Browser-based — instant and private",
    ],
    faqs: [
      { q: "What is Base64 used for?", a: "Base64 is commonly used by developers to embed image files directly in HTML or CSS, encode data for API requests, and safely transmit binary data as text." },
      { q: "Can I encode an image file?", a: "Yes. You can upload an image and get its Base64 data URI string, ready to use in your code." },
    ],
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    slug: "json-formatter",
    description: "Format, validate, and minify JSON data instantly",
    longDescription: "Paste any raw JSON string and instantly format it with proper indentation, making it easy to read. Validate JSON for errors, minify it to a single line, and copy the result. All done in your browser.",
    icon: "FileType",
    color: "cyan",
    bgGradient: "from-cyan-500 to-blue-600",
    inputFormats: ["JSON"],
    outputFormat: "JSON",
    category: "utility",
    featured: false,
    howTo: [
      "Paste your raw JSON into the editor",
      "Click Format to beautify, or Minify to compress",
      "Validate your JSON for syntax errors",
      "Copy the result to clipboard",
    ],
    features: [
      "Pretty-print JSON with indentation",
      "Minify JSON to single line",
      "Validate JSON and highlight errors",
      "One-click copy to clipboard",
      "Syntax highlighting for readability",
    ],
    faqs: [
      { q: "Can it detect JSON errors?", a: "Yes. If your JSON has syntax errors, the tool will highlight the problem and show an error message." },
      { q: "What is minification?", a: "Minification removes all whitespace and newlines from JSON, making it smaller for use in APIs or code." },
    ],
  },
  {
    id: "qr-generator",
    name: "QR Code Generator",
    slug: "qr-generator",
    description: "Generate custom QR codes for URLs, text, and more",
    longDescription: "Instantly generate a QR code for any URL, text, email, or phone number. Customize the size and download as PNG. All QR codes are generated entirely in your browser — no data is sent to any server.",
    icon: "Layers",
    color: "emerald",
    bgGradient: "from-emerald-500 to-green-600",
    inputFormats: ["Plain Text", "URL"],
    outputFormat: "PNG",
    category: "utility",
    featured: false,
    howTo: [
      "Enter a URL, text, or other data",
      "Your QR code is generated instantly",
      "Adjust the size as needed",
      "Download the QR code as a PNG image",
    ],
    features: [
      "Generate QR codes for URLs, text, email, phone",
      "Adjustable QR code size",
      "Download as PNG",
      "Instant generation — no delay",
      "100% private — no server processing",
    ],
    faqs: [
      { q: "What data can I encode in a QR code?", a: "You can encode URLs, plain text, email addresses, phone numbers, and SMS messages." },
      { q: "What is the maximum data size for a QR code?", a: "QR codes can store up to ~4,000 characters of text or ~2,900 numeric characters." },
    ],
  },
  {
    id: "password-generator",
    name: "Password Generator",
    slug: "password-generator",
    description: "Generate strong, secure random passwords instantly",
    longDescription: "Create strong, random passwords with customizable length and character sets. Choose to include uppercase, lowercase, numbers, and special symbols. Copy your password with one click — nothing is stored or transmitted.",
    icon: "FileOutput",
    color: "orange",
    bgGradient: "from-orange-500 to-red-600",
    inputFormats: ["Settings"],
    outputFormat: "Password",
    category: "utility",
    featured: false,
    howTo: [
      "Set your desired password length",
      "Choose which character types to include",
      "Click Generate to create a new password",
      "Copy it to your clipboard with one click",
    ],
    features: [
      "Customizable length (4-128 characters)",
      "Uppercase, lowercase, numbers, symbols",
      "Cryptographically random generation",
      "One-click copy to clipboard",
      "Never stored or transmitted",
    ],
    faqs: [
      { q: "Are the passwords truly random?", a: "Yes. We use the browser's built-in cryptographic random number generator (crypto.getRandomValues) for maximum security." },
      { q: "Is my password saved anywhere?", a: "No. The password is generated and displayed only in your browser and is never sent to any server." },
    ],
  },
  // ─── NEW UTILITY TOOLS ────────────────────────────────────────────────────
  {
    id: "url-encoder",
    name: "URL Encoder / Decoder",
    slug: "url-encoder",
    description: "Encode or decode URLs and query strings with percent-encoding",
    longDescription: "Convert special characters in URLs to percent-encoded format or decode them back to readable text. Essential for building API requests, sharing links, and working with query strings.",
    icon: "FileType",
    color: "blue",
    bgGradient: "from-blue-500 to-indigo-600",
    inputFormats: ["Plain Text"],
    outputFormat: "URL / Text",
    category: "utility",
    featured: false,
    howTo: ["Choose Encode or Decode mode", "Paste your text or encoded URL", "See the result instantly", "Copy with one click"],
    features: ["URL Encode (encode special chars)", "URL Decode (reverse)", "Swap input/output in one click", "Handles full URLs and query strings", "Instant browser-based conversion"],
    faqs: [
      { q: "What is URL encoding?", a: "URL encoding converts special characters like spaces, &, =, and ? into percent-encoded format (e.g., space becomes %20) so they can be safely used in URLs." },
      { q: "When do I need to decode a URL?", a: "When you receive a URL-encoded string from an API, form submission, or query parameter, decoding reveals the original readable text." },
    ],
  },
  {
    id: "uuid-generator",
    name: "UUID Generator",
    slug: "uuid-generator",
    description: "Generate cryptographically random UUIDs (v4) in bulk",
    longDescription: "Generate one or many random UUID v4 strings instantly. Choose between lowercase and uppercase formats. Copy individual UUIDs or all at once. All UUIDs are generated using the browser's crypto API — no server involvement.",
    icon: "FileOutput",
    color: "purple",
    bgGradient: "from-purple-500 to-indigo-600",
    inputFormats: ["Settings"],
    outputFormat: "UUID",
    category: "utility",
    featured: false,
    howTo: ["Set how many UUIDs to generate (1-20)", "Choose lowercase or uppercase format", "Click Generate", "Copy individual UUIDs or all at once"],
    features: ["Generate 1-20 UUIDs at once", "Lowercase and UPPERCASE formats", "Cryptographically random (crypto.randomUUID)", "One-click copy per UUID or all", "Instant, no server required"],
    faqs: [
      { q: "What is a UUID?", a: "A UUID (Universally Unique Identifier) is a 128-bit label used to uniquely identify objects in software systems. Version 4 UUIDs are randomly generated." },
      { q: "Are these UUIDs truly unique?", a: "UUID v4 uses cryptographic randomness, making the probability of collision astronomically low — effectively unique for all practical purposes." },
    ],
  },
  {
    id: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    slug: "lorem-ipsum",
    description: "Generate placeholder Lorem Ipsum text for your designs",
    longDescription: "Quickly generate Lorem Ipsum placeholder text for mockups, wireframes, and UI designs. Choose paragraphs, sentences, or words, set the count, and optionally start with the classic 'Lorem ipsum' opening.",
    icon: "Type",
    color: "emerald",
    bgGradient: "from-emerald-500 to-teal-600",
    inputFormats: ["Settings"],
    outputFormat: "Text",
    category: "utility",
    featured: false,
    howTo: ["Choose Paragraphs, Sentences, or Words", "Set the count using the slider", "Toggle whether to start with 'Lorem ipsum'", "Click Generate and copy your text"],
    features: ["Paragraphs, sentences, or words output", "Adjustable count (1-200 words, 1-20 sentences)", "Classic Lorem ipsum opening toggle", "One-click copy to clipboard", "Instant generation, no ads"],
    faqs: [
      { q: "What is Lorem Ipsum?", a: "Lorem Ipsum is standard placeholder text used in typography and design since the 1500s. It approximates the natural distribution of letters in Latin text." },
      { q: "Is the generated text the same every time?", a: "No, each generation produces randomized text (except when using the fixed 'Lorem ipsum' opening)." },
    ],
  },
  {
    id: "hash-generator",
    name: "Hash Generator",
    slug: "hash-generator",
    description: "Generate SHA-1, SHA-256, SHA-384, and SHA-512 hash values",
    longDescription: "Generate cryptographic hash values from any text using the browser's built-in Web Crypto API. Supports SHA-1, SHA-256, SHA-384, and SHA-512 algorithms. Useful for verifying data integrity, passwords, and checksums.",
    icon: "FileType",
    color: "indigo",
    bgGradient: "from-indigo-500 to-violet-600",
    inputFormats: ["Plain Text"],
    outputFormat: "Hash",
    category: "utility",
    featured: false,
    howTo: ["Enter or paste any text", "Click Generate Hashes", "All four SHA hash values appear instantly", "Click Copy next to any hash"],
    features: ["SHA-1, SHA-256, SHA-384, SHA-512 support", "Uses Web Crypto API (cryptographically secure)", "Copy any hash with one click", "100% private — no data sent to servers", "Instant generation"],
    faqs: [
      { q: "What are hashes used for?", a: "Hashes are used for password verification, data integrity checks, file checksums, digital signatures, and identifying duplicate data." },
      { q: "Is SHA-1 still secure?", a: "SHA-1 is considered cryptographically weak and should not be used for security-critical applications. Use SHA-256 or higher instead." },
    ],
  },
  {
    id: "color-converter",
    name: "Color Converter",
    slug: "color-converter",
    description: "Convert colors between HEX, RGB, HSL, RGBA, HSLA, and HSV",
    longDescription: "Pick or enter any color and instantly see it converted to HEX, RGB, RGBA, HSL, HSLA, and HSV formats. Perfect for web developers and designers who need color values in different formats for CSS.",
    icon: "Image",
    color: "pink",
    bgGradient: "from-pink-500 to-orange-500",
    inputFormats: ["HEX", "Color Picker"],
    outputFormat: "HEX / RGB / HSL",
    category: "utility",
    featured: false,
    howTo: ["Use the color picker or type a HEX value", "See all format conversions update instantly", "Click Copy next to any format", "Use the value directly in your CSS"],
    features: ["HEX, RGB, RGBA, HSL, HSLA, HSV output", "Visual color picker", "Manual HEX input", "One-click copy per format", "Live real-time preview bar"],
    faqs: [
      { q: "What is the difference between HSL and HSV?", a: "HSL (Hue, Saturation, Lightness) and HSV (Hue, Saturation, Value/Brightness) are both cylindrical color models but differ in how they define brightness." },
      { q: "Can I type a HEX code directly?", a: "Yes. Type any valid 6-digit HEX code (e.g., #6d28d9) in the HEX input field and all formats will update instantly." },
    ],
  },
  {
    id: "csv-to-json",
    name: "CSV to JSON",
    slug: "csv-to-json",
    description: "Convert CSV data to JSON format instantly",
    longDescription: "Paste any CSV data and convert it to a JSON array of objects. The first row is treated as headers. Choose between pretty-printed or minified JSON output and download the result as a .json file.",
    icon: "FileType",
    color: "teal",
    bgGradient: "from-teal-500 to-cyan-600",
    inputFormats: ["CSV"],
    outputFormat: "JSON",
    category: "utility",
    featured: false,
    howTo: ["Paste your CSV data (first row = headers)", "Choose pretty-print or compact output", "Click Convert to JSON", "Copy or download the JSON file"],
    features: ["Auto-detects headers from first row", "Pretty-printed or minified output", "Download as .json file", "One-click copy to clipboard", "Browser-based — no upload needed"],
    faqs: [
      { q: "Does it support quoted fields with commas?", a: "Basic quoted fields are supported. For complex CSV with nested quotes, consider preprocessing the data first." },
      { q: "Can I convert back from JSON to CSV?", a: "Not yet — currently only CSV to JSON is supported. JSON to CSV conversion is planned." },
    ],
  },
  {
    id: "markdown-preview",
    name: "Markdown Preview",
    slug: "markdown-preview",
    description: "Write Markdown and preview the rendered HTML output live",
    longDescription: "A real-time Markdown editor and previewer. Write or paste Markdown and instantly see the rendered HTML output. Switch between split view, preview-only, or HTML output mode. Copy the generated HTML with one click.",
    icon: "FileText",
    color: "orange",
    bgGradient: "from-orange-500 to-amber-600",
    inputFormats: ["Markdown"],
    outputFormat: "HTML",
    category: "utility",
    featured: false,
    howTo: ["Write or paste your Markdown text", "See a live preview in split view", "Switch to HTML Output mode to see the generated code", "Copy the HTML or keep editing"],
    features: ["Real-time Markdown preview", "Split view, preview, and HTML output modes", "Supports headings, bold, italic, links, lists", "Copy HTML with one click", "No external libraries — fast and private"],
    faqs: [
      { q: "What Markdown features are supported?", a: "Headings (H1-H6), bold, italic, inline code, links, images, blockquotes, unordered and ordered lists, and horizontal rules." },
      { q: "Can I use this as a Markdown editor?", a: "Yes. You can write your Markdown here and use the HTML output in any web project or CMS." },
    ],
  },
  {
    id: "text-diff",
    name: "Text Diff Tool",
    slug: "text-diff",
    description: "Compare two texts and highlight added and removed lines",
    longDescription: "Paste two versions of a text and instantly see what changed. Added lines are highlighted in green, removed lines in red, and unchanged lines are shown as-is. Useful for comparing code, documents, or any text.",
    icon: "FileText",
    color: "cyan",
    bgGradient: "from-cyan-500 to-teal-600",
    inputFormats: ["Plain Text"],
    outputFormat: "Diff",
    category: "utility",
    featured: false,
    howTo: ["Paste the original text in the left editor", "Paste the modified text in the right editor", "Click Compare Texts", "Review the highlighted differences"],
    features: ["Line-by-line comparison", "Color-coded output (green = added, red = removed)", "Summary stats (added/removed/unchanged lines)", "Works with any plain text or code", "100% browser-based — private"],
    faqs: [
      { q: "Can I compare code files?", a: "Yes. Paste any code text into both fields and the diff will highlight exactly which lines changed." },
      { q: "Is there a text length limit?", a: "There is no enforced limit, though very large texts may be slower to process in the browser." },
    ],
  },
  {
    id: "base-converter",
    name: "Number Base Converter",
    slug: "base-converter",
    description: "Convert numbers between Binary, Octal, Decimal, and Hexadecimal",
    longDescription: "Instantly convert any number between Binary (base 2), Octal (base 8), Decimal (base 10), and Hexadecimal (base 16). Type your number, select the source base, and see all conversions update in real time.",
    icon: "Type",
    color: "violet",
    bgGradient: "from-violet-500 to-indigo-600",
    inputFormats: ["Number"],
    outputFormat: "Binary / Hex / Decimal",
    category: "utility",
    featured: false,
    howTo: ["Select the input base (Binary, Octal, Decimal, or Hex)", "Type your number", "See all other base conversions instantly", "Copy any result with one click"],
    features: ["Binary, Octal, Decimal, Hex support", "Real-time conversion as you type", "Input validation per base", "Copy any format with one click", "Color-coded to highlight current base"],
    faqs: [
      { q: "What is hexadecimal used for?", a: "Hexadecimal (base 16) is widely used in programming for memory addresses, color codes (e.g., #FF5733), and binary data representation." },
      { q: "What numbers are valid in binary?", a: "Binary only accepts 0 and 1. Any other digit will be rejected with an error message." },
    ],
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export const toolCategories = {
  image: tools.filter((t) => t.category === "image"),
  pdf: tools.filter((t) => t.category === "pdf"),
  text: tools.filter((t) => t.category === "text"),
  utility: tools.filter((t) => t.category === "utility"),
};
